# Site settings
title: જય જલારામ રસાવાળાખમણ
email: jayjalaramrasawala@gmail.com
url: https://jayjalaram.github.io
description: "jay jalaram rasawala Khaman Punagam Surat. It is Farsan shop. Our business is started in 2012. We start our business with a little stall near  punagam circal. At our shop we sell a khaman, Idada, vagharelakhaman Rasawala khaman, Rasawala SAMOSA, Samosa with chatni etc."
keywords: "khaman, samosa, rasawalakhaman"
skills: "Rasawala - Khaman - Samosa"
meta_author: jay jalaram

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: જય જલારામ રસાવાળાખમણ
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rasawalakhaman
  - title: facebook
    url: https://www.facebook.com/jayjalaram.rasawalakhaman
  - title: github
    url: http://github.com/jayjalaram

# Postal address (add as many lines as necessary)
address:
  - line: Shop 02 Opp. Punagam health center
  - line: Surat, Gujarat, 395010

# Credits content
credits: 'Created and maintain by <a href="https://github.com/bhaveshpp">Bhavesh Prajapati</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
